// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAsset(arg1:string,arg2:string):Promise<Record<string, string>>;

export function AddTemplate(arg1:main.TemplateInput):Promise<Record<string, string>>;

export function Analyze(arg1:Record<string, string>):Promise<Record<string, any>>;

export function Chat(arg1:string,arg2:Array<Record<string, string>>,arg3:Record<string, any>):Promise<main.chatResult>;

export function ChooseStorageDirectory():Promise<Record<string, any>>;

export function CreatePack(arg1:string,arg2:main.PackInput):Promise<Record<string, boolean>>;

export function CreateProject(arg1:main.ProjectInput):Promise<Record<string, string>>;

export function CreateTryOn(arg1:main.TryOnInput):Promise<Record<string, any>>;

export function DeleteProject(arg1:string):Promise<Record<string, boolean>>;

export function DeleteTemplate(arg1:string):Promise<Record<string, boolean>>;

export function DeleteTryOn(arg1:string):Promise<Record<string, boolean>>;

export function DownloadAsset(arg1:string):Promise<boolean>;

export function GenerateAsset(arg1:string):Promise<Record<string, boolean>>;

export function GeneratePack(arg1:string):Promise<Record<string, boolean>>;

export function ImportURL(arg1:string):Promise<Record<string, string>>;

export function LatestCreation():Promise<Record<string, any>>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function Logout():Promise<Record<string, boolean>>;

export function Me():Promise<Record<string, any>>;

export function Models():Promise<Record<string, any>>;

export function NotifyGeneration(arg1:string,arg2:string):Promise<void>;

export function PickImage():Promise<Record<string, string>>;

export function PollHuabotAuthorization(arg1:string):Promise<Record<string, any>>;

export function Project(arg1:string):Promise<Record<string, any>>;

export function Projects():Promise<Array<Record<string, any>>>;

export function RefreshModels():Promise<Record<string, any>>;

export function RefreshTokenSettings():Promise<Record<string, any>>;

export function RegenerateTryOn(arg1:string):Promise<Record<string, boolean>>;

export function ResetPrompt(arg1:string):Promise<Record<string, string>>;

export function SaveSettings(arg1:main.SettingsInput):Promise<Record<string, boolean>>;

export function StartHuabotAuthorization():Promise<main.deviceAuthorization>;

export function StorageLocation():Promise<Record<string, any>>;

export function Templates():Promise<Array<Record<string, any>>>;

export function TokenSettings():Promise<Record<string, any>>;

export function TryOnJob(arg1:string):Promise<Record<string, any>>;

export function TryOnJobs(arg1:number,arg2:number):Promise<Record<string, any>>;

export function UpdateAsset(arg1:string,arg2:main.AssetPatch):Promise<Record<string, boolean>>;

export function UpdateTemplate(arg1:string,arg2:main.TemplateInput):Promise<Record<string, boolean>>;

export function Upload(arg1:string,arg2:string,arg3:Array<number>):Promise<Record<string, string>>;
