// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTemplate(arg1) {
  return window['go']['main']['Studio']['AddTemplate'](arg1);
}

export function Analyze(arg1) {
  return window['go']['main']['Studio']['Analyze'](arg1);
}

export function Chat(arg1, arg2) {
  return window['go']['main']['Studio']['Chat'](arg1, arg2);
}

export function ChooseStorageDirectory() {
  return window['go']['main']['Studio']['ChooseStorageDirectory']();
}

export function CreatePack(arg1, arg2) {
  return window['go']['main']['Studio']['CreatePack'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['main']['Studio']['CreateProject'](arg1);
}

export function CreateTryOn(arg1) {
  return window['go']['main']['Studio']['CreateTryOn'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['Studio']['DeleteProject'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['Studio']['DeleteTemplate'](arg1);
}

export function DeleteTryOn(arg1) {
  return window['go']['main']['Studio']['DeleteTryOn'](arg1);
}

export function GenerateAsset(arg1) {
  return window['go']['main']['Studio']['GenerateAsset'](arg1);
}

export function GeneratePack(arg1) {
  return window['go']['main']['Studio']['GeneratePack'](arg1);
}

export function ImportURL(arg1) {
  return window['go']['main']['Studio']['ImportURL'](arg1);
}

export function LatestCreation() {
  return window['go']['main']['Studio']['LatestCreation']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['Studio']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['Studio']['Logout']();
}

export function Me() {
  return window['go']['main']['Studio']['Me']();
}

export function Models() {
  return window['go']['main']['Studio']['Models']();
}

export function NotifyGeneration(arg1, arg2) {
  return window['go']['main']['Studio']['NotifyGeneration'](arg1, arg2);
}

export function PickImage() {
  return window['go']['main']['Studio']['PickImage']();
}

export function Project(arg1) {
  return window['go']['main']['Studio']['Project'](arg1);
}

export function Projects() {
  return window['go']['main']['Studio']['Projects']();
}

export function RegenerateTryOn(arg1) {
  return window['go']['main']['Studio']['RegenerateTryOn'](arg1);
}

export function ResetPrompt(arg1) {
  return window['go']['main']['Studio']['ResetPrompt'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['Studio']['SaveSettings'](arg1);
}

export function StorageLocation() {
  return window['go']['main']['Studio']['StorageLocation']();
}

export function Templates() {
  return window['go']['main']['Studio']['Templates']();
}

export function TokenSettings() {
  return window['go']['main']['Studio']['TokenSettings']();
}

export function TryOnJob(arg1) {
  return window['go']['main']['Studio']['TryOnJob'](arg1);
}

export function TryOnJobs(arg1, arg2) {
  return window['go']['main']['Studio']['TryOnJobs'](arg1, arg2);
}

export function UpdateAsset(arg1, arg2) {
  return window['go']['main']['Studio']['UpdateAsset'](arg1, arg2);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['main']['Studio']['Upload'](arg1, arg2, arg3);
}
